# numpy

##  基础操作

In [10]:
# numpy.array
import numpy as np
data=np.arange(15).reshape(3,5)
data.shape

(3, 5)

In [ ]:
# np.ones & np.ones 
# zeros(shape, dtype=float, order='C')
np.zeros(10,dtype=np.float64)
# 创建二维的矩阵
np.zeros((3,5))

In [ ]:
# np.arange 
# 生成一个由启示 终止 和 步长 决定的numpy矩阵
np.arange(0,10,2)

In [11]:
# np.linspace
# 给定一个范围攫取多少点,右侧为包括此范围
# np.linspace(['start', 'stop', 'num=50', 'endpoint=True', 'retstep=False', 'dtype=None', 'axis=0'])
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
#np.random
#生成随机数,前闭后开
# randint(low, high=None, size=None, dtype='l')
np.random.seed(666)
np.random.randint(0,10,size=(3,4))

In [ ]:
"""
np.random.normal
loc：float
此概率分布的均值（对应着整个分布的中心centre）
scale：float
此概率分布的标准差（对应于分布的宽度，scale越大越矮胖，scale越小，越瘦高）
"""
# normal(loc=0.0, scale=1.0, size=None)
np.random.normal(10,2,(2,2))

In [ ]:
# 构造数组
x = np.arange(15).reshape(3,5)
# 维度
x.ndim
# 维度元组
x.shape
# 元素个数
x.size
# 可以用-1代替不确定
x = x.reshape(5,-1) 

In [12]:
# 数据访问,截取,拷贝
# 索引特定元素的方法
print("索引: "+str(x[1,0]))
# 切片操作
print("切片操作: "+str(x[1:3:1,2:4:1]))
# 取某一行
print("取某一行: "+str(x[0:1:1,::]))
# 取某一列
print("取某一列: "+str(x[0::,0:1:1]))
# 深度拷贝
sub_x = x[0::,0:1:1].copy()

索引: 3
切片操作: [[5]
 [8]]
取某一行: [[0 1 2]]
取某一列: [[ 0]
 [ 3]
 [ 6]
 [ 9]
 [12]]


## 合并和分割

In [13]:
# 合并操作
x = np.array([[1,2,3],[4,5,6]])
print(np.concatenate((x,x),axis=1))
print(np.row_stack([x,x]))
print(np.column_stack([x,x]))
# print(np.hstack([x,x]))
# print(np.vstack([x,x]))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [14]:
# 分离操作
# numpy.split(ary, indices_or_sections, axis)
# indices_or_sections：果是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭）
# np.hsplit & np.vsplit
X1,X2,X3 = np.split(x,[1,2],axis=1)
print(X1)
print(X2)
print(X3)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


## 数学与矩阵运算

In [ ]:
print(np.arange(1,13))

In [ ]:
# 加减乘除
print(x+3)
print(x-3)
print(x*3)
print(x/3)

In [ ]:
# 函数数学运算
print(np.max(x))
print(np.min(x))
print(np.log10(x))
print(np.exp(x))

In [16]:
# 两个矩阵运算
A = np.arange(12).reshape(3,4)
B = np.arange(12).reshape(4,3)
print(A)
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [17]:
# 点乘法,矩阵乘法
print(A.dot(B))
# 转置
print(A.T)
# 向量和矩阵运算
a = np.arange(4)
print(A * a)
# 矩阵的逆运算，逆矩阵
# np.linalg.inv()
a = np.array([[1,2,3],
              [4,5,7],
              [7,8,9]])
print(a.dot(np.linalg.pinv(a)))

[[ 42  48  54]
 [114 136 158]
 [186 224 262]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]]
[[ 1.00000000e+00  2.33146835e-15 -1.66533454e-16]
 [-1.66533454e-16  1.00000000e+00  9.43689571e-16]
 [-2.77555756e-16  3.33066907e-16  1.00000000e+00]]


## 张量中的特征

In [18]:
# 和
print(np.sum(a,axis=1))
# 乘积
print(np.product(a,axis=1))
# 中位数,平均数,可以加axis
print(np.mean(a))
print(np.median(a))
# 百分位点求值
a = np.arange(100)
print(np.percentile(a,q=25))

[ 6 16 24]
[  6 140 504]
5.111111111111111
5.0
24.75


## 排序乱序生成序列

In [19]:
# 打乱循序
np.random.shuffle(a)
print(a)
# 排序
a.sort()
print(a)
# 生成某个条件索引
print(a<50)
# 将索引序号传入
print(a[a>50])
# 有任意满足某一条件
print(np.any(a>20))
# 全部满足某一条件
print(np.all(a>20))
# 两个 求 交集用 & 位运算
print(np.sum((a>3) & (a<8)))

[90 52 79 74 38 35 77 65 95 61 40 96 19  3 16 43 58 26 94 23  8 29  5 71
 66 22 10 31 70 86 85 13 46 51  7  9 83 69 24  0 64 78 76 11 33 55 27 68
 25 28 89 98  6 20 15 57 92 32 56 50 49 82 39 75 63 91 84 62 18 97 44 80
  2 53 81 37 54 87 67 72 73 88 48  4 21 41 93 47  1 42 45 59 60 34 99 36
 30 14 17 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False False False False False False False False False
 False False False Fals